### PR TITLE
Make maximum static inline (fixes 'undefined symbol: maximum')

### PR DESCRIPTION
**Pull request by krassowski**
(1126, "Can't open shared library 'levenshtein.so' (errno: 11, undefined symbol: maximum)").

### CODE REVIEW

**Comment by juanmirocks** [comment]
@krassowski this is awesome, thank you for your contribution!!

I should test this and do the merge within this week -- Otherwise please ping me again.

**Comment by krassowski** [comment]
:ping_pong:

**Comment by juanmirocks** [comment]
Damn it -- Thank you so much @krassowski; have some patience please :) - I will get back to this asap.

**Comment by juanmirocks** [comment]
This should certainly have taken me less time, but 1 month later, big thanks @krassowski !! 

I only removed from your README instructions the flag you put `-fPIC` -- I don't think it's needed.

Regarding the instructions on MariaDB, I currently cannot test that, so I take your word for it :)

BIG THANK YOU !

**Comment by krassowski** [comment]
Thanks!

You are right, I should have explained why I added `-fPIC`: compiling without `-fPIC` on linux x64 raises linking error:
```
gcc -o levenshtein.so -shared levenshtein.c `mysql_config --include`
/usr/bin/ld: /tmp/cctYKyKN.o: relocation R_X86_64_PC32 against symbol `levenshtein' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```

As long as user has a nice version of ld they will be instructed to add `-fPIC` flag so that's not a big deal.

**Comment by juanmirocks** [comment]
Excellent, thanks for the clarification.

I added a comment to the command regarding the -fPIC flag: https://github.com/juanmirocks/Levenshtein-MySQL-UDF/commit/e6da92e13e2c025d719436a0474d67515817150c

That should do :)

**Pull request merged**
